---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  clusterIP: None
  ports:
    - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.1.1
          env:
            - name: "ELASTICSEARCH_URL"
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: ELASTICSEARCH_HOSTS
          ports:
            - containerPort: 5601