---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: backend
        role: slave
    spec:
      containers:
        - name: redis-slave
          image: redis
          command: ["bash"]
          args: ["-c", "redis-server --slaveof $(REDIS_MASTER_HOST) 6379"]
          env:
            - name: "REDIS_MASTER_HOST"
              valueFrom:
                configMapKeyRef:
                  name: main-config
                  key: REDIS_MASTER_HOST
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379